name: CI
on:
  push:
    branches:
      - main

 permissions:
      id-token: write
      contents: read
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::843987575744:role/github-actions-cloud-project
          aws-region: eu-west-2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Test application
        run: python -m py_compile app/app.py

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t my-cloud-app:latest ./app

      - name: Push Docker image
        run: |
          docker tag my-cloud-app:latest 843987575744.dkr.ecr.eu-west-2.amazonaws.com/my-cloud-app:latest
          docker push 843987575744.dkr.ecr.eu-west-2.amazonaws.com/my-cloud-app:latest

      - name: Deploy to EC2
        run: |
          aws ssm send-command \
            --instance-ids i-0c95479e4cd3bc45d \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "docker pull 843987575744.dkr.ecr.eu-west-2.amazonaws.com/my-cloud-app:latest",
              "docker stop my-cloud-app || true",
              "docker rm my-cloud-app || true",
              "docker run -d --name my-cloud-app -p 80:5000 --restart unless-stopped 843987575744.dkr.ecr.eu-west-2.amazonaws.com/my-cloud-app:latest"
            ]' \
            --region eu-west-2
